name: programming_course
description: "A new Flutter project."

publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  smooth_page_indicator: ^1.1.0
  go_router: ^14.0.0
  cloud_firestore: ^4.17.2
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  firebase_storage: ^11.7.4
  flutter_bloc: ^8.1.5
  image_picker: ^1.1.0
  shimmer: ^3.0.0
  gradient_borders: ^1.0.0
  iconsax: ^0.0.8
  equatable: ^2.0.5
  firebase_authentication_repository:
    path: packages/firebase_auth_repository
  intl: ^0.19.0
  date_picker_plus: ^3.0.2
  another_flushbar: ^1.12.30
  firebase_app_check: ^0.2.2+4
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.3
  chat_bubbles: ^1.6.0
  cached_network_image: ^3.3.1
  flutter_dotenv: ^5.1.0
  file_picker: ^8.0.3
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/badges/
    - asset/certificates/
    - asset/icons/
    - asset/illustrations/
    - asset/images/
    - asset/logos/
    - asset/.env
  fonts:
    - family: SF Pro Text
      fonts:
        - asset: asset/fonts/SFProText-Regular.ttf
        - asset: asset/fonts/SFProText-Bold.ttf
        - asset: asset/fonts/SF-Pro-Text-Semibold.otf
          weight: 800
