name: firebase_authentication_repository

environment:
  sdk: ">=3.1.5 <4.0.0"


dev_dependencies:
  flutter_lints: ^3.0.1

dependencies:
  equatable: ^2.0.5
  google_sign_in: ^6.2.1
  firebase_auth: ^4.16.0


